# Generated by Django 2.1.5 on 2019-02-18 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecte',
            name='grup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='projecte',
            name='productOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productOwner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projecte',
            name='scrumMaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrumMaster', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spec',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spec',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Sprint'),
        ),
    ]
